name: catboost_ml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - catboost
  - shap
  - pip
  - pip:
      - scikit-optimize